name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  memoryhub:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tianting-v2
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -q

      - name: Run benchmark
        run: python scripts/benchmark_memoryhub.py --memories 10000 --recalls 500 