name: MemoryHub CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tianting-v2
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-dev
      
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pysimdjson
          # 关键：指向绝对路径，避免 cwd 变化带来的混淆
          pip install -e ${{ github.workspace }}/tianting-v2/src
      
      - name: Run tests
        run: |
          pytest tests/test_memoryhub/ -v
      
      - name: Run benchmark (Linux - 10k/500)
        run: |
          python scripts/benchmark_memoryhub.py --memories 10000 --recalls 500 --index auto

  windows-test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: tianting-v2
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install -e ${{ github.workspace }}/tianting-v2/src
      
      - name: Run tests
        run: |
          pytest tests/test_memoryhub/ -v
      
      - name: Run benchmark (Windows - 1k/50)
        run: |
          python scripts/benchmark_memoryhub.py --memories 1000 --recalls 50 --index auto
