name: MemoryHub CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-dev
      
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install -e ./src
      
      - name: Run tests
        run: |
          PYTHONPATH=./src pytest tests/test_memoryhub/test_basic_roaring.py -v
      
      - name: Run benchmark (Linux - 10k/500)
        run: |
          PYTHONPATH=./src python scripts/benchmark_memoryhub.py --memories 10000 --recalls 500 --index auto

  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install -e ./src
      
      - name: Run tests
        run: |
          $env:PYTHONPATH = "./src"
          pytest tests/test_memoryhub/test_basic_roaring.py -v
      
      - name: Run benchmark (Windows - 1k/50)
        run: |
          $env:PYTHONPATH = "./src"
          python scripts/benchmark_memoryhub.py --memories 1000 --recalls 50 --index auto